### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Irv1n** [PhilippCo/meas_rpi#1]
when installing, i have errors:
`Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/packaging.py", line 55, in check_dist_requires_python
    if not check_requires_python(requires_python):
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/packaging.py", line 33, in check_requires_python
    return python_version in requires_python_specifier
  File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/specifiers.py", line 676, in __contains__
    return self.contains(item)
  File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/specifiers.py", line 681, in contains
    item = parse(item)
  File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 28, in parse
    return Version(version)
  File "/usr/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 219, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object`

**Comment by PhilippCo** [comment]
Thanks a lot for the hint!
What was your setup?

**Comment by PhilippCo** [comment]
I tried an installation on a raspberry pi 4 today and it worked without issues

**Comment by Irv1n** [comment]
all okey with this error. If install on clear system
But now new error whith: scipy 


 Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpx0x_fz0j_in_process.py get_requires_for_build_wheel /tmp/tmpxkfdwmvg
       cwd: /tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a
  Complete output (66 lines):
  The Meson build system
  Version: 0.63.3
  Source dir: /tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a
  Build dir: /tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a/.mesonpy-sgxfozxu/build
  Build type: native build
  Project name: SciPy
  Project version: 1.9.2
  C compiler for the host machine: cc (gcc 10.2.1 "cc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
  C linker for the host machine: cc ld.bfd 2.35.2
  C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
  C++ linker for the host machine: c++ ld.bfd 2.35.2
  Host machine cpu family: arm
  Host machine cpu: armv7l
  Compiler for C supports arguments -Wno-unused-but-set-variable: YES
  Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
  Compiler for C supports arguments -Wno-unused-function: YES
  Compiler for C supports arguments -Wno-conversion: YES
  Compiler for C supports arguments -Wno-misleading-indentation: YES
  Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
  Library m found: YES

  ../../meson.build:49:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
  The following exception(s) were encountered:
  Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
  Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
  Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
  Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
  Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
  Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
  Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
  Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
  Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
  Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
  Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
  Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"

  A full log can be found at /tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a/.mesonpy-sgxfozxu/build/meson-logs/meson-log.txt
  + meson setup --native-file=/tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/usr /tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a /tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a/.mesonpy-sgxfozxu/build
  Traceback (most recent call last):
    File "/tmp/tmpx0x_fz0j_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpx0x_fz0j_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpx0x_fz0j_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
      with _project(config_settings) as project:
    File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
      return next(self.gen)
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 948, in _project
      with Project.with_temp_working_dir(
    File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
      return next(self.gen)
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
      yield cls(source_dir, tmpdir, build_dir)
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 682, in __init__
      self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 713, in _configure
      self._meson(
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 696, in _meson
      return self._proc('meson', *args)
    File "/tmp/pip-build-env-rjrjbi6z/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 691, in _proc
      subprocess.check_call(list(args))
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/usr', '/tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a', '/tmp/pip-install-qhi_xi7r/scipy_bf2d1b141ddb490d908fef08a4ed965a/.mesonpy-sgxfozxu/build']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/17/07/68df07679ec4a4a24bff00147a14908aa73e9e8912d142886e8d0e1e3d64/scipy-1.9.2.tar.gz#sha256=99e7720caefb8bca6ebf05c7d96078ed202881f61e0c68bd9e0f3e8097d6f794 (from https://pypi.org/simple/scipy/) (requires-python:>=3.8). Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpx0x_fz0j_in_process.py get_requires_for_build_wheel /tmp/tmpxkfdwmvg Check the logs for full command output.

**Comment by mendip-defender** [comment]
I had the same issue on a pi2. It seems to be an issue with pip on python, doing a "pip install --upgrade pip" seemed to solve that issue.

**Comment by PhilippCo** [comment]
Thanks a lot for your contribution!

Should we try to add a pip install --upgrade pip?

I will try an installation on a fresh Pi4 tomorrow.

**Comment by mendip-defender** [comment]
I get,
`Collecting scipy
  Downloading scipy-1.9.3.tar.gz (42.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 1.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      The Meson build system
      Version: 0.63.3
      Source dir: /tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427
      Build dir: /tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427/.mesonpy-9wyqcigi/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Host machine cpu family: arm
      Host machine cpu: armv7l
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES

      ../../meson.build:57:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"

      A full log can be found at /tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427/.mesonpy-9wyqcigi/build/meson-logs/meson-log.txt
      + meson setup --native-file=/tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/usr /tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427 /tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427/.mesonpy-9wyqcigi/build
      Traceback (most recent call last):
        File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "/tmp/pip-build-env-vjjt7qjq/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/usr', '/tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427', '/tmp/pip-install-og2x598p/scipy_0d02b7e64dbb47d09c11e978183d9427/.mesonpy-9wyqcigi/build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

So once the script is finished I might see if I need to add Gfortran.

**Comment by mendip-defender** [comment]
Well, it is still refusing to compile SciPy. I think its down to the use of Meson and that is kind of causing lots to break. I did find some chatter about it and I get a feeling it is a typical Linux thing of blaming the user for not having these things ready and not knowing the middle name of the person who soldered the chip in place. I think 1.8.2 installs on your script but it is a pain that insists on trying, 1.9.3, 1.9.2, 1.9.1, 1.9.0 each one of them taking 5mins to realise this.

**Comment by PhilippCo** [comment]
I was able to reproduce that on a Pi4.

"sudo apt install gfortran libopenblas-dev liblapack-dev"
Seems to be needed before one is able to install the latest scipy (1.9.3) version

I will add that to the install script

**Comment by PhilippCo** [comment]
I added the packages in the install.sh. This time the installation run without errors
